version: 2
defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:10.16.3

jobs:
  build:
    <<: *defaults
    steps:
      - run: echo "$PUBLIC_REGISTRY:_authToken=$PUBLIC_REGISTRY_TOKEN" >> ~/.npmrc
      - checkout
      - run: yarn install
      - run: yarn deploy
  docs-deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - '17:16:87:45:9e:a8:89:a1:c2:ed:62:72:7b:dc:fa:ed'
      - checkout
      - run: yarn install
      - run: yarn docs
      - run: yarn global add gh-pages
      - run: git config user.email "circleci@circleci.com"
      - run: git config user.name "circleci"
      - run: npx gh-pages --dist docs
workflows:
  version: 2

  btd:
    jobs:
      - build:
          context: NPM
      - docs-deploy
